name = "ethblk"
type = "module"

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "18.04"
release_mask = "5.0.0-16.*"

[[supported_kernels]]
distro_type = "Ubuntu"
distro_release = "18.04"
release_mask = "4.18.0-21.*"
