language: go

go:
  - master

os:
  - linux

dist:
  - xenial

addons:
  apt:
    packages:
    - qemu

services:
  - docker

before_script:
  - go get -u code.dumpstack.io/tools/out-of-tree
  - out-of-tree bootstrap
  - out-of-tree kernel autogen

script:
  - out-of-tree pew
